### ISSUE TITLE
Formulieren verzenden

### ISSUE THREAD

**Issue by Kabouterhuisje** [Kabouterhuisje/PosterHouse#20]
Op de contactpagina moet het mogelijk zijn om formulieren te verzenden. Op dit moment doet de form nog niks.

**Comment by ShaunVanBeurden** [comment]
Moet mogelijk een lokale mailserver op worden gezet om deze functie te testen

**Comment by Kabouterhuisje** [comment]
Opties: 
- Mailserver
- Database tabel
