### ISSUE TITLE
Categorienamen in dropdown weergeven

### ISSUE THREAD

**Issue by Kabouterhuisje** [Kabouterhuisje/PosterHouse#33]
Op het admin panel moeten de categorienamen (incl subcategorienamen in een dropdown menu weergegeven worden. Nu staan er cijfers die je kunt aanpassen en dat is niet gebruiksvriendelijk.

**Comment by ShaunVanBeurden** [comment]
Ook voor het toevoegen van een product een dropdown voor de categorie
